-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 11:20:35 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boye_base
-- -----------------------------------------------------
-- 系统基础框架

-- -----------------------------------------------------
-- Schema boye_base
--
-- 系统基础框架
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boye_base` DEFAULT CHARACTER SET utf8 ;
USE `boye_base` ;

-- -----------------------------------------------------
-- Table `boye_base`.`common_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_action` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` CHAR(30) NOT NULL DEFAULT '' COMMENT '行为唯一标识',
  `title` CHAR(80) NOT NULL DEFAULT '' COMMENT '行为说明',
  `remark` CHAR(140) NOT NULL DEFAULT '' COMMENT '行为描述',
  `rule` TEXT NULL DEFAULT NULL COMMENT '行为规则',
  `log` TEXT NULL DEFAULT NULL COMMENT '日志规则',
  `type` TINYINT(2) UNSIGNED NOT NULL DEFAULT '1' COMMENT '类型',
  `status` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '状态',
  `update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COMMENT = '系统行为表'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `boye_base`.`common_action_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_action_log` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '执行用户id',
  `action_ip` BIGINT(20) NOT NULL COMMENT '执行行为者ip',
  `model` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '触发行为的表',
  `record_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '触发行为的数据id',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '日志备注',
  `status` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '状态',
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '执行行为的时间',
  `action_id` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `action_ip_ix` (`action_ip` ASC),
  INDEX `user_id_ix` (`user_id` ASC),
  INDEX `fk_common_action_log_common_action1_idx` (`action_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '行为日志表'
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `boye_base`.`common_province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_province` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `provinceID` VARCHAR(6) NOT NULL,
  `province` VARCHAR(40) NOT NULL,
  `countryid` INT(11) NOT NULL DEFAULT '1017' COMMENT '国家ID\n',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boye_base`.`common_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cityID` VARCHAR(6) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `father` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_common_city_common_province_idx` (`father` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 809
DEFAULT CHARACTER SET = utf8
COMMENT = '省市区中的市级数据';


-- -----------------------------------------------------
-- Table `boye_base`.`common_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_area` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `areaID` VARCHAR(50) NOT NULL,
  `area` VARCHAR(60) NOT NULL,
  `father` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_common_area_common_city1_idx` (`father` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3145
DEFAULT CHARACTER SET = utf8
COMMENT = '省市区中的区域';


-- -----------------------------------------------------
-- Table `boye_base`.`common_auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_auth_group` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` CHAR(100) NOT NULL DEFAULT '',
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `rules` CHAR(200) NOT NULL DEFAULT '',
  `menulist` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '可视菜单ID集合',
  `notes` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '描述说明备注不超过120个字符',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COMMENT = '角色权限描述';


-- -----------------------------------------------------
-- Table `boye_base`.`common_auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_auth_rule` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '规则id,自增主键',
  `module` VARCHAR(20) NOT NULL COMMENT '规则所属module',
  `type` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '1-url;2-主菜单',
  `name` CHAR(80) NOT NULL DEFAULT '' COMMENT '规则唯一英文标识',
  `title` CHAR(20) NOT NULL DEFAULT '' COMMENT '规则中文描述',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否有效(0:无效,1:有效)',
  `condition` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '规则附加条件',
  `fid` INT(11) NOT NULL DEFAULT '0' COMMENT '权限对应关联资源id',
  PRIMARY KEY (`id`),
  INDEX `module` (`module` ASC, `status` ASC, `type` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '接口权限描述表（系统暂未用到）';


-- -----------------------------------------------------
-- Table `boye_base`.`common_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_config` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '配置ID',
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '配置名称',
  `type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '配置类型',
  `title` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '配置说明',
  `group` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '配置分组',
  `extra` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '配置值',
  `remark` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '配置说明',
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `status` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '状态',
  `value` TEXT NULL DEFAULT NULL COMMENT '配置值',
  `sort` SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_name` (`name` ASC),
  INDEX `type` (`type` ASC),
  INDEX `group` (`group` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8
COMMENT = '系统配置表';


-- -----------------------------------------------------
-- Table `boye_base`.`common_datatree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_datatree` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(32) NOT NULL COMMENT '节点编码，唯一',
  `name` VARCHAR(64) NOT NULL COMMENT '节点名称',
  `sort` TINYINT(2) NOT NULL COMMENT '排序',
  `createtime` INT(11) NOT NULL COMMENT '创建时间',
  `updatetime` INT(11) NOT NULL COMMENT '更新时间',
  `parents` VARCHAR(256) NOT NULL COMMENT '所有上级的ID，以，隔开，足够支持10级了',
  `parentid` INT(11) NOT NULL COMMENT '父节点ID',
  `notes` VARCHAR(128) NOT NULL COMMENT '备注',
  `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '所处层级',
  `iconurl` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '小图标地址\n',
  `uid` INT(11) NOT NULL DEFAULT '0' COMMENT '所属用户ID，0为全局',
  `hidden_value` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '隐藏值',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boye_base`.`common_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_log` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id，自增',
  `timestamp` INT(10) NOT NULL COMMENT '创建时间',
  `remote_addr` VARCHAR(255) NULL DEFAULT NULL COMMENT '客户端IP',
  `request_uri` VARCHAR(1024) NULL DEFAULT NULL COMMENT '请求url',
  `context` TEXT NOT NULL COMMENT '上下文环境Session，Cookie之类',
  `info` TEXT NOT NULL COMMENT '记录信息',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '系统异常日志';


-- -----------------------------------------------------
-- Table `boye_base`.`itboye_ucenter_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`itboye_ucenter_member` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` CHAR(16) NOT NULL COMMENT '用户名',
  `password` CHAR(32) NOT NULL COMMENT '密码',
  `email` CHAR(32) NOT NULL COMMENT '用户邮箱',
  `mobile` CHAR(15) NOT NULL DEFAULT '' COMMENT '用户手机',
  `reg_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '注册时间',
  `reg_ip` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '注册IP',
  `last_login_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最后登录时间',
  `last_login_ip` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '最后登录IP',
  `update_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `status` TINYINT(4) NULL DEFAULT '0' COMMENT '用户状态',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `status` (`status` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `boye_base`.`common_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_member` (
  `uid` INT(10) UNSIGNED NOT NULL,
  `realname` CHAR(16) NOT NULL COMMENT '真实姓名',
  `idnumber` CHAR(32) NOT NULL COMMENT '身份证号',
  `nickname` CHAR(16) NOT NULL DEFAULT '' COMMENT '昵称',
  `sex` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '性别',
  `birthday` DATE NOT NULL DEFAULT '0000-00-00' COMMENT '生日',
  `qq` CHAR(10) NOT NULL DEFAULT '' COMMENT 'qq号',
  `score` MEDIUMINT(8) NOT NULL DEFAULT '0' COMMENT '用户积分',
  `login` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '登录次数',
  `reg_ip` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '注册IP',
  `reg_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '注册时间',
  `last_login_ip` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '最后登录IP',
  `last_login_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最后登录时间',
  `update_time` INT(10) UNSIGNED NOT NULL COMMENT '最新更新时间',
  `status` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '会员状态',
  INDEX `status` (`status` ASC),
  INDEX `fk_common_member_itboye_ucenter_member1_idx` (`uid` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '会员信息表';


-- -----------------------------------------------------
-- Table `boye_base`.`common_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_menu` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文档ID',
  `title` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '标题',
  `pid` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '上级分类ID',
  `sort` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序（同级有效）',
  `url` CHAR(255) NOT NULL DEFAULT '' COMMENT '链接地址',
  `hide` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否隐藏',
  `tip` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '提示',
  `group` VARCHAR(50) NULL DEFAULT '' COMMENT '分组',
  `is_dev` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否仅开发者模式可见',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`),
  INDEX `pid` (`pid` ASC),
  INDEX `status` (`status` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 280
DEFAULT CHARACTER SET = utf8
COMMENT = '系统菜单表\n';


-- -----------------------------------------------------
-- Table `boye_base`.`common_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_organization` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `orgcode` VARCHAR(64) NOT NULL COMMENT '组织机构编码',
  `orgname` VARCHAR(128) NOT NULL COMMENT '组织机构名称',
  `father` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '父节点',
  `path` TEXT NOT NULL COMMENT '路径',
  `notes` VARCHAR(128) NOT NULL COMMENT '备注',
  `create_time` INT(11) NOT NULL COMMENT '创建时间',
  `update_time` INT(11) NOT NULL COMMENT '更新时间',
  `sort` INT(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `level` INT(11) NOT NULL DEFAULT '0' COMMENT '所处层级',
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `path` (`path` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COMMENT = '组织机构表\n';


-- -----------------------------------------------------
-- Table `boye_base`.`itboye_ucenter_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`itboye_ucenter_admin` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '管理员ID',
  `status` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '管理员状态',
  `member_id` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itboye_ucenter_admin_itboye_ucenter_member1_idx` (`member_id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '总管理员表';


-- -----------------------------------------------------
-- Table `boye_base`.`itboye_ucenter_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`itboye_ucenter_app` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '应用ID',
  `app_id` CHAR(32) NOT NULL COMMENT 'appid随机生成',
  `title` VARCHAR(30) NOT NULL COMMENT '应用名称',
  `url` VARCHAR(100) NOT NULL COMMENT '应用URL',
  `ip` CHAR(15) NOT NULL DEFAULT '' COMMENT '应用IP',
  `auth_key` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '加密KEY',
  `sys_login` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '同步登陆',
  `allow_ip` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '允许访问的IP',
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `status` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '应用状态',
  PRIMARY KEY (`id`),
  INDEX `status` (`status` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '应用表';


-- -----------------------------------------------------
-- Table `boye_base`.`itboye_ucenter_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`itboye_ucenter_setting` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '设置ID',
  `type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '配置类型（1-用户配置）',
  `value` TEXT NOT NULL COMMENT '配置数据',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '设置表';


-- -----------------------------------------------------
-- Table `boye_base`.`common_organization_has_common_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_organization_has_common_organization` (
  `common_organization_id` BIGINT(20) NOT NULL,
  `common_organization_id1` BIGINT(20) NOT NULL,
  PRIMARY KEY (`common_organization_id`, `common_organization_id1`),
  INDEX `fk_common_organization_has_common_organization_common_organ_idx` (`common_organization_id1` ASC),
  INDEX `fk_common_organization_has_common_organization_common_organ_idx1` (`common_organization_id` ASC),
  CONSTRAINT `fk_common_organization_has_common_organization_common_organiz1`
    FOREIGN KEY (`common_organization_id`)
    REFERENCES `boye_base`.`common_organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_common_organization_has_common_organization_common_organiz2`
    FOREIGN KEY (`common_organization_id1`)
    REFERENCES `boye_base`.`common_organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boye_base`.`common_organization_has_common_organization1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_organization_has_common_organization1` (
  `common_organization_id` BIGINT(20) NOT NULL,
  `common_organization_id1` BIGINT(20) NOT NULL,
  PRIMARY KEY (`common_organization_id`, `common_organization_id1`),
  INDEX `fk_common_organization_has_common_organization1_common_orga_idx` (`common_organization_id1` ASC),
  INDEX `fk_common_organization_has_common_organization1_common_orga_idx1` (`common_organization_id` ASC),
  CONSTRAINT `fk_common_organization_has_common_organization1_common_organi1`
    FOREIGN KEY (`common_organization_id`)
    REFERENCES `boye_base`.`common_organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_common_organization_has_common_organization1_common_organi2`
    FOREIGN KEY (`common_organization_id1`)
    REFERENCES `boye_base`.`common_organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boye_base`.`common_org_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_org_member` (
  `organization_id` BIGINT(20) NOT NULL,
  `member_uid` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`organization_id`, `member_uid`),
  INDEX `fk_common_organization_has_itboye_ucenter_member_itboye_uce_idx` (`member_uid` ASC),
  INDEX `fk_common_organization_has_itboye_ucenter_member_common_org_idx` (`organization_id` ASC),
  CONSTRAINT `fk_common_organization_has_itboye_ucenter_member_common_organ1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `boye_base`.`common_organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_common_organization_has_itboye_ucenter_member_itboye_ucent1`
    FOREIGN KEY (`member_uid`)
    REFERENCES `boye_base`.`itboye_ucenter_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boye_base`.`common_auth_group_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boye_base`.`common_auth_group_access` (
  `group_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `uid` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`group_id`, `uid`),
  INDEX `fk_common_auth_group_has_itboye_ucenter_member_itboye_ucent_idx` (`uid` ASC),
  INDEX `fk_common_auth_group_has_itboye_ucenter_member_common_auth__idx` (`group_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
